[package]
name = "fractal_gl"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe="0.20.1"
egui_glow = "0.20.1"
glow = "0.11.0"
log = "0.4.17"
simple_logger = "4.0.0"
emath = "0.20.0"